[project]
name = "araxne"
version = "0.0.1"
authors = [
  { name="Tytus Dunin", email="tm.dunin@student.uw.edu.pl" },
]
description = "A simple algorithm for quantifying how much two strings rhyme in Polish"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "GPL-3.0"
license-files = ["LICENSE"]

[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project.urls]
Homepage = "https://github.com/pypa/araxne"
Issues = "https://github.com/pypa/araxne/issues"